# Generated by Django 4.2.8 on 2026-03-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xacminh',
            name='GiaiTrinhSV',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
