# Generated by Django 4.2.29 on 2026-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xacminh',
            name='DuongDanFile',
            field=models.FileField(blank=True, null=True, upload_to='xac_minh/'),
        ),
        migrations.AddField(
            model_name='xacminh',
            name='TenFile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
