# Generated by Django 4.2.29 on 2026-03-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_xacminh_duongdanfile_xacminh_tenfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xacminh',
            old_name='PhanHoi',
            new_name='PhanHoiAdmin',
        ),
        migrations.AddField(
            model_name='xacminh',
            name='GiaiTrinhSV',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
