# Generated by Django 4.2.29 on 2026-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_lichsuhoso'),
    ]

    operations = [
        migrations.AddField(
            model_name='xacminh',
            name='NgayGiaiTrinh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
