# Generated by Django 4.2.29 on 2026-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_vinhdanh_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinhdanh',
            name='HinhAnh',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='featured_faces/'),
        ),
    ]
