# Generated by Django 4.2.29 on 2026-03-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_vinhdanh_hinhanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='HinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to='bai_viet/'),
        ),
    ]
