# Generated by Django 4.2.29 on 2026-03-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_baiviet_hinhanh'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhHeThong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBatDau', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu nộp')),
                ('ThoiGianKetThuc', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc nộp')),
                ('TrangThaiMo', models.BooleanField(default=True, verbose_name='Cổng đang mở')),
                ('ThongBaoHieuLuc', models.CharField(default='Hiện tại đang trong thời gian nộp hồ sơ xét duyệt Sinh viên 5 tốt.', max_length=500, verbose_name='Thông báo khi đang mở')),
                ('ThongBaoHetHan', models.CharField(default='Cổng nộp hồ sơ hiện đang đóng. Vui lòng quay lại sau.', max_length=500, verbose_name='Thông báo khi hết hạn')),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
                'db_table': 'CauHinhHeThong',
            },
        ),
    ]
