# Generated by Django 4.2.29 on 2026-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_cauhinhhethong'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhinhhethong',
            name='HanChotGiaiTrinh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hạn chót giải trình hồ sơ'),
        ),
    ]
