# Generated by Django 4.2.29 on 2026-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minhchung',
            name='SoLuong',
            field=models.IntegerField(default=1),
        ),
    ]
