# Generated by Django 4.2.29 on 2026-03-15 16:15

from django.db import migrations, models
import django.db.models.deletion
import evidences.models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0002_minhchung_soluong'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinhChungFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DuongDanFile', models.FileField(upload_to=evidences.models.minh_chung_upload_path)),
                ('TenFile', models.CharField(blank=True, max_length=255, null=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('MinhChung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_file', to='evidences.minhchung')),
            ],
            options={
                'verbose_name': 'Tệp minh chứng',
                'db_table': 'MinhChungFile',
            },
        ),
    ]
