# Generated by Django 4.2.29 on 2026-03-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0003_minhchungfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinhChungFile',
        ),
    ]
