# Generated by Django 4.2.29 on 2026-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0004_delete_minhchungfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='minhchung',
            name='NgayGiaiTrinh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minhchung',
            name='NgayMinhChung',
            field=models.DateField(blank=True, null=True),
        ),
    ]
